namespace EquityLens.Api.Services.Agents;

public sealed record AgentNodeExecutionPolicy(int TimeoutSeconds, int MaxRetryCount);

/// <summary>Immutable design-time contract. This is the single source of truth for planner, validator and Admin.</summary>
public sealed record AgentNodeContract(
    string NodeType,
    int Version,
    string DisplayName,
    string Description,
    string Stage,
    string SideEffectLevel,
    string InputSchema,
    string OutputSchema,
    IReadOnlyList<string> RequiredBlackboardKeys,
    IReadOnlyList<string> OptionalBlackboardKeys,
    IReadOnlyList<string> ProducedBlackboardKeys,
    IReadOnlyList<string> AllowedPreviousNodeTypes,
    IReadOnlyList<string> AllowedNextNodeTypes,
    AgentNodeExecutionPolicy DefaultPolicy,
    bool IsIdempotent,
    bool SupportsLoop,
    bool RequiresHumanInput);

public sealed record AgentNodeCatalogEntry(AgentNodeContract Contract)
{
    public string NodeType => Contract.NodeType;
    public string DisplayName => Contract.DisplayName;
    public string Description => Contract.Description;
    public string Stage => Contract.Stage;
    public string SideEffectLevel => Contract.SideEffectLevel;
    public IReadOnlyList<string> RequiredBlackboardKeys => Contract.RequiredBlackboardKeys;
    public IReadOnlyList<string> ProducedBlackboardKeys => Contract.ProducedBlackboardKeys;
    public IReadOnlyList<string> AllowedNextNodeTypes => Contract.AllowedNextNodeTypes;
    public AgentNodeExecutionPolicy DefaultPolicy => Contract.DefaultPolicy;
}
public sealed record AgentWorkflowCatalogEntry(string WorkflowType, string DisplayName, string Description, string AgentType, IReadOnlyList<string> NodeTypes, IReadOnlyList<(string From, string To)> Edges);

public interface IAgentWorkflowCatalog
{
    IReadOnlyList<AgentWorkflowCatalogEntry> Workflows { get; }
    IReadOnlyList<AgentNodeCatalogEntry> Nodes { get; }
    AgentWorkflowCatalogEntry GetWorkflow(string workflowType);
    AgentNodeCatalogEntry GetNode(string nodeType);
}

public sealed class AgentWorkflowCatalog : IAgentWorkflowCatalog
{
    public IReadOnlyList<AgentNodeCatalogEntry> Nodes { get; } =
    [
        N(FeedbackRevisionNodeTypes.LoadContext, "載入使用者修正內容", "載入父研究、原答案、引用、Critic 與使用者 feedback。", "Input", "ReadOnly", [AgentBlackboardKeys.ParentAgentRunId], [AgentBlackboardKeys.ParentResearchRunId, AgentBlackboardKeys.ResearchRunId, AgentBlackboardKeys.ResearchRequest, AgentBlackboardKeys.Ticker, AgentBlackboardKeys.Question, AgentBlackboardKeys.Answer, AgentBlackboardKeys.OriginalAnswer, AgentBlackboardKeys.ResearchIntent, AgentBlackboardKeys.InitialEvidence, AgentBlackboardKeys.SelectedEvidence, AgentBlackboardKeys.Citations, AgentBlackboardKeys.Candidates, AgentBlackboardKeys.FeedbackComment, AgentBlackboardKeys.FeedbackIntent, AgentBlackboardKeys.RevisionContext], [FeedbackRevisionNodeTypes.ValidateContext]),
        N(FeedbackRevisionNodeTypes.ValidateContext, "驗證修正內容", "驗證 feedback 與父子研究關聯後交由 Planner 動態組 DAG。", "Planning", "ReadOnly", [AgentBlackboardKeys.RevisionContext, AgentBlackboardKeys.FeedbackComment], [], [ResearchInvestigationNodeTypes.PlanRetrieval, ResearchInvestigationNodeTypes.DraftAnswer]),
        N(CriticReviewNodeTypes.LoadResearchRun, "載入研究結果", "載入既有 Research Run。", "Load", "ReadOnly", [AgentBlackboardKeys.ResearchRunId], [AgentBlackboardKeys.Ticker, AgentBlackboardKeys.Question, AgentBlackboardKeys.ResearchRun, AgentBlackboardKeys.Answer, AgentBlackboardKeys.Citations, AgentBlackboardKeys.Steps, AgentBlackboardKeys.Candidates], [CriticReviewNodeTypes.BuildEvidencePacket]),
        N(CriticReviewNodeTypes.BuildEvidencePacket, "建立證據封包", "整理供評論使用的證據。", "Evidence", "ReadOnly", [AgentBlackboardKeys.ResearchRun, AgentBlackboardKeys.Answer], [AgentBlackboardKeys.EvidencePacket], [CriticReviewNodeTypes.CheckEvidence]),
        N(CriticReviewNodeTypes.CheckEvidence, "檢查證據", "進行 deterministic evidence coverage 檢查。", "Analyze", "ReadOnly", [AgentBlackboardKeys.EvidencePacket], [AgentBlackboardKeys.EvidenceChecks, AgentBlackboardKeys.CriticFindings], [CriticReviewNodeTypes.CritiqueAnswer]),
        N(CriticReviewNodeTypes.CritiqueAnswer, "評論答案", "由 Critic Agent 評估答案品質。", "Analyze", "ExternalLlmRead", [AgentBlackboardKeys.EvidencePacket, AgentBlackboardKeys.EvidenceChecks, AgentBlackboardKeys.Answer], [AgentBlackboardKeys.CriticReview, AgentBlackboardKeys.CriticFindings], [CriticReviewNodeTypes.FinalizeCriticReport]),
        N(CriticReviewNodeTypes.FinalizeCriticReport, "完成評論報告", "產生評論結果與路由決策。", "Finalize", "WritesAgentTrace", [AgentBlackboardKeys.CriticReview], [AgentBlackboardKeys.FinalOutput], [DraftRevisionNodeTypes.DraftRevisedAnswer]),
        N(DraftRevisionNodeTypes.LoadCriticReviewRun, "載入評論結果", "載入已完成的 Critic Review。", "Load", "ReadOnly", [AgentBlackboardKeys.CriticReviewRunId], [AgentBlackboardKeys.CriticReviewRun, AgentBlackboardKeys.Ticker, AgentBlackboardKeys.Question, AgentBlackboardKeys.Answer, AgentBlackboardKeys.CriticReview, AgentBlackboardKeys.CriticFindings], [DraftRevisionNodeTypes.DraftRevisedAnswer]),
        N(DraftRevisionNodeTypes.DraftRevisedAnswer, "產生修正版", "依評論結果產生修正版答案。", "Act", "ExternalLlmRead", [AgentBlackboardKeys.CriticReview, AgentBlackboardKeys.CriticFindings, AgentBlackboardKeys.Answer], [AgentBlackboardKeys.RevisedAnswer, AgentBlackboardKeys.RevisionSummary, AgentBlackboardKeys.AppliedRecommendation], [DraftRevisionNodeTypes.FinalizeRevision]),
        N(DraftRevisionNodeTypes.FinalizeRevision, "完成修正版", "輸出最終修正版。", "Finalize", "WritesAgentTrace", [AgentBlackboardKeys.CriticReview, AgentBlackboardKeys.Answer, AgentBlackboardKeys.RevisedAnswer, AgentBlackboardKeys.RevisionSummary], [AgentBlackboardKeys.FinalOutput], [])
        ,N(PortfolioDiagnosisNodeTypes.LoadContext, "載入投組診斷內容", "驗證投組與診斷期間。", "Load", "ReadOnly", ["portfolioId"], ["portfolioContext"], [PortfolioDiagnosisNodeTypes.ResolveRiskEvidence])
        ,N(PortfolioDiagnosisNodeTypes.ResolveRiskEvidence, "重用既有 Risk Run", "驗證已持久化 Risk Run 的日期與 input hash，將相容結果寫入標準化風險證據。", "Evidence", "ReadOnly", [AgentBlackboardKeys.PortfolioContext], [AgentBlackboardKeys.PortfolioRiskEvidence, AgentBlackboardKeys.CoreRiskCalculationRequired, AgentBlackboardKeys.MathResults], [PortfolioRiskMathNodeTypes.PrepareInputs])
        ,N(PortfolioDiagnosisNodeTypes.CalculateAttribution, "計算績效歸因", "計算投組相對基準及標的／產業貢獻。", "Analyze", "ReadOnly", ["portfolioContext"], ["performanceAttribution"], [PortfolioDiagnosisNodeTypes.LoadRiskProfile])
        ,N(PortfolioDiagnosisNodeTypes.LoadRiskProfile, "載入風險概況", "載入既有風險治理與資料品質結果。", "Analyze", "ReadOnly", ["portfolioContext"], ["riskProfile"], [PortfolioDiagnosisNodeTypes.PrioritizeRiskAnalyses])
        ,N(PortfolioDiagnosisNodeTypes.PrioritizeRiskAnalyses, "排序風險分析", "依資料品質及治理警示排序應補做分析。", "Decide", "ReadOnly", ["performanceAttribution", "riskProfile"], ["riskAnalysisPriorities"], [PortfolioDiagnosisNodeTypes.EvaluateQuality])
        ,N(PortfolioDiagnosisNodeTypes.EvaluateQuality, "投組診斷品質閘門", "Deterministic 檢查資料覆蓋與必要風險分析，產生可執行 gaps。", "Validation", "ReadOnly", [AgentBlackboardKeys.PortfolioContext, AgentBlackboardKeys.PerformanceAttribution, AgentBlackboardKeys.RiskProfile, AgentBlackboardKeys.MathResults], [AgentBlackboardKeys.PortfolioDiagnosisQuality, AgentBlackboardKeys.PortfolioDiagnosisGaps], [PortfolioRiskMathNodeTypes.Execute, PortfolioDiagnosisNodeTypes.BuildEvidencePacket], supportsLoop: true)
        ,N(PortfolioDiagnosisNodeTypes.BuildEvidencePacket, "建立投組證據封包", "建立可追溯的診斷證據快照。", "Evidence", "ReadOnly", ["performanceAttribution", "riskProfile", "riskAnalysisPriorities", AgentBlackboardKeys.PortfolioDiagnosisQuality], ["portfolioEvidencePacket"], [PortfolioDiagnosisNodeTypes.DraftDiagnosis])
        ,N(PortfolioDiagnosisNodeTypes.DraftDiagnosis, "撰寫投組診斷", "以已驗證的證據生成繁體中文診斷。", "Draft", "ExternalLlmRead", ["portfolioEvidencePacket"], ["portfolioDiagnosisDraft"], [PortfolioDiagnosisNodeTypes.FinalizeDiagnosis])
        ,N(PortfolioDiagnosisNodeTypes.FinalizeDiagnosis, "批准並發布投組診斷", "人工批准後驗證並輸出最終投組診斷。", "Finalize", "WritesAgentTrace", ["portfolioDiagnosisDraft"], ["finalOutput"], [], requiresHumanInput: true)
        ,N(PortfolioDiagnosisNodeTypes.FinalizeRejectedDiagnosis, "完成遭拒絕的投組診斷", "人工拒絕診斷後記錄決策並將 run 標為失敗。", "Finalize", "WritesAgentTrace", [AgentBlackboardKeys.HumanApproval], ["finalOutput"], [])
        ,N(EvidenceRemediationNodeTypes.LoadContext, "載入補證據內容", "載入 Critic Review 的持久化研究快照與證據缺口。", "Input", "ReadOnly", [AgentBlackboardKeys.CriticReviewRunId], [AgentBlackboardKeys.CriticReviewRun, AgentBlackboardKeys.ResearchRunId, AgentBlackboardKeys.Ticker, AgentBlackboardKeys.Question, AgentBlackboardKeys.Answer, AgentBlackboardKeys.Citations, AgentBlackboardKeys.Candidates, AgentBlackboardKeys.CriticFindings, AgentBlackboardKeys.CriticReview], [EvidenceRemediationNodeTypes.PlanRetrieval])
        ,N(EvidenceRemediationNodeTypes.PlanRetrieval, "規劃補充檢索", "依研究問題與 Critic findings 建立有界檢索計畫。", "Planning", "ReadOnly", [AgentBlackboardKeys.Question, AgentBlackboardKeys.CriticFindings], [AgentBlackboardKeys.RetrievalPlan], [EvidenceRemediationNodeTypes.RetrieveEvidence])
        ,N(EvidenceRemediationNodeTypes.RetrieveEvidence, "檢索本地補充證據", "檢索本地文件；舊 workflow snapshot 可保留既有 Web fallback。", "Retrieval", "ExternalRead", [AgentBlackboardKeys.Ticker, AgentBlackboardKeys.RetrievalPlan], [AgentBlackboardKeys.RetrievedEvidence], [EvidenceRemediationNodeTypes.ExtractClaims])
        ,N(EvidenceRemediationNodeTypes.RetrieveWebEvidence, "檢索 Web 證據", "依受控 search intents 檢索候選證據；暫時性 Web 故障耗盡重試後降級為零結果。", "Retrieval", "ExternalRead", [AgentBlackboardKeys.Question, AgentBlackboardKeys.ExtractedClaims], [AgentBlackboardKeys.RetrievedEvidence], [EvidenceRemediationNodeTypes.AssessSupport])
        ,N(EvidenceRemediationNodeTypes.ExtractClaims, "擷取待驗證 Claims", "由答案擷取 claims，經品質閘門修復或 deterministic decomposition 後才供檢索使用。", "Analysis", "ExternalLlmRead", [AgentBlackboardKeys.Question, AgentBlackboardKeys.Answer, AgentBlackboardKeys.CriticFindings], [AgentBlackboardKeys.ExtractedClaims, AgentBlackboardKeys.ClaimSetValidation, AgentBlackboardKeys.RequiredResearchDimensions, AgentBlackboardKeys.MissingResearchDimensions, AgentBlackboardKeys.ClaimRepairHistory], [EvidenceRemediationNodeTypes.RetrieveWebEvidence, EvidenceRemediationNodeTypes.AssessSupport])
        ,N(EvidenceRemediationNodeTypes.AssessSupport, "Evidence Assessor", "評估補充證據對各 claim 的語義支持程度與分析影響。", "Analysis", "ExternalLlmRead", [AgentBlackboardKeys.Question, AgentBlackboardKeys.Answer, AgentBlackboardKeys.CriticFindings, AgentBlackboardKeys.ExtractedClaims, AgentBlackboardKeys.RetrievedEvidence], [AgentBlackboardKeys.ClaimSupportAssessments], [EvidenceRemediationNodeTypes.ValidateMappings])
        ,N(EvidenceRemediationNodeTypes.ValidateMappings, "驗證證據映射", "Deterministic 驗證 citation、數值映射與重新分析訊號。", "Validation", "ReadOnly", [AgentBlackboardKeys.ExtractedClaims, AgentBlackboardKeys.RetrievedEvidence, AgentBlackboardKeys.ClaimSupportAssessments], [AgentBlackboardKeys.EvidenceValidationResults], [EvidenceRemediationNodeTypes.BuildPacket])
        ,N(EvidenceRemediationNodeTypes.Route, "決定補證據路由", "依驗證結果決定完成或進入下一輪，並保存重新分析建議。", "Routing", "ReadOnly", [AgentBlackboardKeys.EvidenceValidationResults], [AgentBlackboardKeys.RouteDecision, AgentBlackboardKeys.UnresolvedClaims, AgentBlackboardKeys.RequiresReanalysis, AgentBlackboardKeys.ReanalysisReasons], [EvidenceRemediationNodeTypes.PlanRetrieval, EvidenceRemediationNodeTypes.BuildPacket])
        ,N(EvidenceRemediationNodeTypes.BuildPacket, "建立補證據封包", "建立可追蹤的 claim-citation 證據封包。", "Evidence", "ReadOnly", [AgentBlackboardKeys.EvidenceValidationResults, AgentBlackboardKeys.RetrievedEvidence], [AgentBlackboardKeys.RemediatedEvidencePacket], [EvidenceRemediationNodeTypes.DraftRevision])
        ,N(EvidenceRemediationNodeTypes.DraftRevision, "產生證據修正版", "只使用已驗證的證據生成修正版。", "Generation", "ExternalLlmRead", [AgentBlackboardKeys.Answer, AgentBlackboardKeys.RemediatedEvidencePacket], [AgentBlackboardKeys.RevisedAnswer, AgentBlackboardKeys.RevisionSummary], [EvidenceRemediationNodeTypes.Finalize])
        ,N(EvidenceRemediationNodeTypes.Finalize, "完成補證據流程", "輸出修正版、補充證據狀態與未解決 claims。", "Finalization", "WritesAgentTrace", [AgentBlackboardKeys.Answer, AgentBlackboardKeys.RevisedAnswer, AgentBlackboardKeys.RevisionSummary, AgentBlackboardKeys.EvidenceValidationResults], [AgentBlackboardKeys.FinalOutput], [])
        ,N(EvidenceReanalysisNodeTypes.Load, "載入補證據結果", "載入需要重新分析的 EvidenceRemediation 持久化結果。", "Input", "ReadOnly", [AgentBlackboardKeys.EvidenceRemediationRunId], [AgentBlackboardKeys.EvidenceRemediationOutput, AgentBlackboardKeys.RemediatedEvidencePacket, AgentBlackboardKeys.ReanalysisReasons], [EvidenceReanalysisNodeTypes.Validate])
        ,N(EvidenceReanalysisNodeTypes.Validate, "驗證重新分析請求", "驗證重新分析理由、claims 與 evidence mappings。", "Validation", "ReadOnly", [AgentBlackboardKeys.EvidenceRemediationOutput, AgentBlackboardKeys.RemediatedEvidencePacket, AgentBlackboardKeys.ReanalysisReasons], [], [EvidenceReanalysisNodeTypes.BuildContext])
        ,N(EvidenceReanalysisNodeTypes.BuildContext, "建立分析內容", "只以已驗證 claims 與證據建立重新分析內容。", "Evidence", "ReadOnly", [AgentBlackboardKeys.RemediatedEvidencePacket, AgentBlackboardKeys.ReanalysisReasons], [AgentBlackboardKeys.AnalysisContext], [EvidenceReanalysisNodeTypes.Reanalyze])
        ,N(EvidenceReanalysisNodeTypes.Reanalyze, "重新執行投資分析", "依已驗證新證據重新推導受影響結論。", "Analysis", "ExternalLlmRead", [AgentBlackboardKeys.AnalysisContext], [AgentBlackboardKeys.ReanalysisDraft], [EvidenceReanalysisNodeTypes.Critique])
        ,N(EvidenceReanalysisNodeTypes.Critique, "審查重新分析", "由獨立 Critic Agent 檢查證據使用與過度推論。", "Critic", "ExternalLlmRead", [AgentBlackboardKeys.AnalysisContext, AgentBlackboardKeys.ReanalysisDraft], [AgentBlackboardKeys.ReanalysisCriticReview, AgentBlackboardKeys.ReanalysisPolicyDecision], [EvidenceReanalysisNodeTypes.Revise])
        ,N(EvidenceReanalysisNodeTypes.Revise, "修訂重新分析", "依 Critic 結果固定執行一次受控修訂。", "Generation", "ExternalLlmRead", [AgentBlackboardKeys.ReanalysisDraft, AgentBlackboardKeys.ReanalysisCriticReview, AgentBlackboardKeys.ReanalysisPolicyDecision], [AgentBlackboardKeys.ReanalysisFinalRevision], [EvidenceReanalysisNodeTypes.Finalize])
        ,N(EvidenceReanalysisNodeTypes.Finalize, "完成重新分析", "輸出重新分析、最終答案、Critic 結果與下一步建議。", "Finalization", "WritesAgentTrace", [AgentBlackboardKeys.AnalysisContext, AgentBlackboardKeys.ReanalysisDraft, AgentBlackboardKeys.ReanalysisFinalRevision], [AgentBlackboardKeys.FinalOutput], [])
        ,N(ResearchInvestigationNodeTypes.Validate, "驗證研究請求", "驗證股票、來源與研究資料可用性。", "Input", "ReadOnly", [AgentBlackboardKeys.ResearchRequest], [AgentBlackboardKeys.Ticker], [ResearchInvestigationNodeTypes.DetectIntent])
        ,N(ResearchInvestigationNodeTypes.DetectIntent, "辨識研究意圖", "辨識風險、財務、展望或一般研究意圖。", "Planning", "ReadOnly", [AgentBlackboardKeys.Question], [AgentBlackboardKeys.ResearchIntent], [ResearchInvestigationNodeTypes.PlanRetrieval])
        ,N(ResearchInvestigationNodeTypes.PlanRetrieval, "規劃初始檢索", "建立首次研究檢索策略並初始化證據集合。", "Planning", "ReadOnly", [AgentBlackboardKeys.ResearchRequest, AgentBlackboardKeys.ResearchIntent], [AgentBlackboardKeys.RetrievalPlan, AgentBlackboardKeys.InitialEvidence], [ResearchInvestigationNodeTypes.RetrieveLocal, ResearchInvestigationNodeTypes.EvaluateEvidence])
        ,N(ResearchInvestigationNodeTypes.RetrieveLocal, "檢索本地研究證據", "依來源政策檢索本地文件。", "Evidence", "ExternalRead", [AgentBlackboardKeys.Ticker, AgentBlackboardKeys.RetrievalPlan], [AgentBlackboardKeys.InitialEvidence], [ResearchInvestigationNodeTypes.EvaluateEvidence])
        ,N(ResearchInvestigationNodeTypes.EvaluateEvidence, "評估 Web 能力需求", "Node Agent 只能向 Blackboard 提出 Web capability request，由 Planner 與 Validator 審核。", "Decide", "ExternalLlmRead", [AgentBlackboardKeys.InitialEvidence, AgentBlackboardKeys.ResearchRequest], [AgentBlackboardKeys.InitialEvidencePolicy, AgentBlackboardKeys.CapabilityRequestAssessment, AgentBlackboardKeys.CapabilityRequests], [ResearchInvestigationNodeTypes.RetrieveWeb, ResearchInvestigationNodeTypes.RankEvidence])
        ,N(ResearchInvestigationNodeTypes.RetrieveWeb, "檢索 Web 研究證據", "依來源政策條件式檢索 Web。", "Evidence", "ExternalRead", [AgentBlackboardKeys.InitialEvidencePolicy, AgentBlackboardKeys.Question], [AgentBlackboardKeys.InitialEvidence], [ResearchInvestigationNodeTypes.RankEvidence])
        ,N(ResearchInvestigationNodeTypes.RankEvidence, "排序與選擇研究證據", "Rerank 並選出生成答案使用的證據。", "Evidence", "ExternalRead", [AgentBlackboardKeys.InitialEvidence, AgentBlackboardKeys.ResearchIntent], [AgentBlackboardKeys.SelectedEvidence], [ResearchInvestigationNodeTypes.DraftAnswer])
        ,N(ResearchInvestigationNodeTypes.DraftAnswer, "產生研究初稿", "只使用已選證據產生附引用研究答案。", "Draft", "ExternalLlmRead", [AgentBlackboardKeys.SelectedEvidence, AgentBlackboardKeys.Question], [AgentBlackboardKeys.Answer, AgentBlackboardKeys.Citations, AgentBlackboardKeys.Candidates, AgentBlackboardKeys.ResearchRun], [CriticReviewNodeTypes.BuildEvidencePacket])
        ,N(PortfolioRiskMathNodeTypes.PrepareInputs, "準備投組風險數學輸入", "從授權的市場價格與投組資料建立可追溯數學輸入。", "Evidence", "ReadOnly", [], [AgentBlackboardKeys.MathInputs], [PortfolioRiskMathNodeTypes.Execute])
        ,N(PortfolioRiskMathNodeTypes.Execute, "執行投組風險數學", "使用已驗證 Blackboard 輸入執行 allowlisted 數學函數。", "Analyze", "ReadOnly", [AgentBlackboardKeys.MathInputs], [AgentBlackboardKeys.MathResults], [ResearchInvestigationNodeTypes.DraftAnswer, PortfolioDiagnosisNodeTypes.CalculateAttribution, PortfolioDiagnosisNodeTypes.EvaluateQuality, PortfolioDiagnosisNodeTypes.BuildEvidencePacket], supportsLoop: true)
        ,new(new AgentNodeContract(HumanApprovalNodeTypes.WaitForHumanApproval, 1, "等待人工批准", "暫停 workflow 直到審核者批准或拒絕；決策寫回 Blackboard 後由條件 Edge 分流。", "Approval", "ExternalHumanInteraction", $"{HumanApprovalNodeTypes.WaitForHumanApproval}Input", $"{HumanApprovalNodeTypes.WaitForHumanApproval}Output", [], [AgentBlackboardKeys.ApprovalRequest], [AgentBlackboardKeys.ApprovalRequest, AgentBlackboardKeys.HumanApproval], [], [PortfolioDiagnosisNodeTypes.FinalizeDiagnosis, PortfolioDiagnosisNodeTypes.FinalizeRejectedDiagnosis], new AgentNodeExecutionPolicy(120, 0), true, false, false))
    ];

    public IReadOnlyList<AgentWorkflowCatalogEntry> Workflows { get; } =
    [
        new(AgentWorkflowTypes.CriticReview, "Critic Review", "檢查研究答案與證據品質。", AgentTypes.Critic, [CriticReviewNodeTypes.LoadResearchRun, CriticReviewNodeTypes.BuildEvidencePacket, CriticReviewNodeTypes.CheckEvidence, CriticReviewNodeTypes.CritiqueAnswer, CriticReviewNodeTypes.FinalizeCriticReport], [(CriticReviewNodeTypes.LoadResearchRun, CriticReviewNodeTypes.BuildEvidencePacket), (CriticReviewNodeTypes.BuildEvidencePacket, CriticReviewNodeTypes.CheckEvidence), (CriticReviewNodeTypes.CheckEvidence, CriticReviewNodeTypes.CritiqueAnswer), (CriticReviewNodeTypes.CritiqueAnswer, CriticReviewNodeTypes.FinalizeCriticReport)]),
        new(AgentWorkflowTypes.DraftRevision, "Draft Revision", "根據評論產生修正版研究答案。", AgentTypes.Draft, [DraftRevisionNodeTypes.LoadCriticReviewRun, DraftRevisionNodeTypes.DraftRevisedAnswer, DraftRevisionNodeTypes.FinalizeRevision], [(DraftRevisionNodeTypes.LoadCriticReviewRun, DraftRevisionNodeTypes.DraftRevisedAnswer), (DraftRevisionNodeTypes.DraftRevisedAnswer, DraftRevisionNodeTypes.FinalizeRevision)]),
        new(AgentWorkflowTypes.ResearchQualityReview, "研究品質審查", "檢查研究答案與證據品質後產生修正版。", AgentTypes.Critic, [ResearchQualityReviewNodeTypes.LoadResearchRun, ResearchQualityReviewNodeTypes.BuildEvidencePacket, ResearchQualityReviewNodeTypes.CheckEvidence, ResearchQualityReviewNodeTypes.CritiqueAnswer, ResearchQualityReviewNodeTypes.FinalizeCriticReport, ResearchQualityReviewNodeTypes.DraftRevisedAnswer, ResearchQualityReviewNodeTypes.FinalizeRevision], [(ResearchQualityReviewNodeTypes.LoadResearchRun, ResearchQualityReviewNodeTypes.BuildEvidencePacket), (ResearchQualityReviewNodeTypes.BuildEvidencePacket, ResearchQualityReviewNodeTypes.CheckEvidence), (ResearchQualityReviewNodeTypes.CheckEvidence, ResearchQualityReviewNodeTypes.CritiqueAnswer), (ResearchQualityReviewNodeTypes.CritiqueAnswer, ResearchQualityReviewNodeTypes.FinalizeCriticReport), (ResearchQualityReviewNodeTypes.FinalizeCriticReport, ResearchQualityReviewNodeTypes.DraftRevisedAnswer), (ResearchQualityReviewNodeTypes.DraftRevisedAnswer, ResearchQualityReviewNodeTypes.FinalizeRevision)])
        ,new(AgentWorkflowTypes.PortfolioDiagnosis, "Portfolio Diagnosis", "優先重用已持久化 Risk Run，僅對風險缺口進行動態補算。", AgentTypes.Portfolio, [PortfolioDiagnosisNodeTypes.LoadContext, PortfolioDiagnosisNodeTypes.ResolveRiskEvidence, PortfolioRiskMathNodeTypes.PrepareInputs, PortfolioRiskMathNodeTypes.Execute, PortfolioDiagnosisNodeTypes.CalculateAttribution, PortfolioDiagnosisNodeTypes.LoadRiskProfile, PortfolioDiagnosisNodeTypes.PrioritizeRiskAnalyses, PortfolioDiagnosisNodeTypes.EvaluateQuality, PortfolioDiagnosisNodeTypes.BuildEvidencePacket, PortfolioDiagnosisNodeTypes.DraftDiagnosis, PortfolioDiagnosisNodeTypes.FinalizeDiagnosis], [(PortfolioDiagnosisNodeTypes.LoadContext, PortfolioDiagnosisNodeTypes.ResolveRiskEvidence), (PortfolioDiagnosisNodeTypes.ResolveRiskEvidence, PortfolioRiskMathNodeTypes.PrepareInputs), (PortfolioRiskMathNodeTypes.PrepareInputs, PortfolioRiskMathNodeTypes.Execute), (PortfolioRiskMathNodeTypes.Execute, PortfolioDiagnosisNodeTypes.CalculateAttribution), (PortfolioDiagnosisNodeTypes.CalculateAttribution, PortfolioDiagnosisNodeTypes.LoadRiskProfile), (PortfolioDiagnosisNodeTypes.LoadRiskProfile, PortfolioDiagnosisNodeTypes.PrioritizeRiskAnalyses), (PortfolioDiagnosisNodeTypes.PrioritizeRiskAnalyses, PortfolioDiagnosisNodeTypes.EvaluateQuality)])
        ,new(AgentWorkflowTypes.EvidenceRemediation, "證據補強與修訂", "依 Critic findings 補充證據並產生可驗證修正版。", AgentTypes.Research, EvidenceRemediationTypes(), EvidenceRemediationEdges())
        ,new(AgentWorkflowTypes.EvidenceReanalysis, "證據驅動重新分析", "依已驗證補充證據重新分析、獨立審查並完成一次修訂。", AgentTypes.Analysis, EvidenceReanalysisTypes(), EvidenceReanalysisEdges())
        ,new(AgentWorkflowTypes.ResearchInvestigation, "Research Investigation", "從研究問題、證據檢索、初稿到品質審查與動態修訂的端到端流程。", AgentTypes.Research, ResearchInvestigationTypes(), ResearchInvestigationEdges())
        ,new(AgentWorkflowTypes.FeedbackRevision, "Feedback Revision", "根據使用者修正要求由 Planner 動態組合研究修訂 DAG。", AgentTypes.Research, FeedbackRevisionTypes(), [(FeedbackRevisionNodeTypes.LoadContext, FeedbackRevisionNodeTypes.ValidateContext)])
    ];

    public AgentWorkflowCatalogEntry GetWorkflow(string workflowType) => Workflows.Single(x => x.WorkflowType == workflowType);
    public AgentNodeCatalogEntry GetNode(string nodeType) => Nodes.Single(x => x.NodeType == nodeType);
    private static IReadOnlyList<string> EvidenceRemediationTypes() => [EvidenceRemediationNodeTypes.LoadContext, EvidenceRemediationNodeTypes.ExtractClaims, EvidenceRemediationNodeTypes.PlanRetrieval, EvidenceRemediationNodeTypes.RetrieveEvidence, EvidenceRemediationNodeTypes.AssessSupport, EvidenceRemediationNodeTypes.ValidateMappings, EvidenceRemediationNodeTypes.Route, EvidenceRemediationNodeTypes.BuildPacket, EvidenceRemediationNodeTypes.DraftRevision, EvidenceRemediationNodeTypes.Finalize];
    private static IReadOnlyList<(string From, string To)> EvidenceRemediationEdges() => EvidenceRemediationTypes().Zip(EvidenceRemediationTypes().Skip(1), (from, to) => (from, to)).ToList();
    private static IReadOnlyList<string> EvidenceReanalysisTypes() => [EvidenceReanalysisNodeTypes.Load, EvidenceReanalysisNodeTypes.Validate, EvidenceReanalysisNodeTypes.BuildContext, EvidenceReanalysisNodeTypes.Reanalyze, EvidenceReanalysisNodeTypes.Critique, EvidenceReanalysisNodeTypes.Revise, EvidenceReanalysisNodeTypes.Finalize];
    private static IReadOnlyList<(string From, string To)> EvidenceReanalysisEdges() => EvidenceReanalysisTypes().Zip(EvidenceReanalysisTypes().Skip(1), (from, to) => (from, to)).ToList();
    private static IReadOnlyList<string> ResearchInvestigationTypes() => [ResearchInvestigationNodeTypes.Validate, ResearchInvestigationNodeTypes.DetectIntent, ResearchInvestigationNodeTypes.PlanRetrieval, ResearchInvestigationNodeTypes.RetrieveLocal, ResearchInvestigationNodeTypes.EvaluateEvidence, ResearchInvestigationNodeTypes.RetrieveWeb, ResearchInvestigationNodeTypes.RankEvidence, ResearchInvestigationNodeTypes.DraftAnswer, CriticReviewNodeTypes.BuildEvidencePacket, CriticReviewNodeTypes.CheckEvidence, CriticReviewNodeTypes.CritiqueAnswer, CriticReviewNodeTypes.FinalizeCriticReport];
    private static IReadOnlyList<(string From, string To)> ResearchInvestigationEdges() => ResearchInvestigationTypes().Zip(ResearchInvestigationTypes().Skip(1), (from, to) => (from, to)).ToList();
    private static IReadOnlyList<string> FeedbackRevisionTypes() => [FeedbackRevisionNodeTypes.LoadContext, FeedbackRevisionNodeTypes.ValidateContext, ..ResearchInvestigationTypes(), ..EvidenceRemediationTypes(), ..EvidenceReanalysisTypes(), DraftRevisionNodeTypes.DraftRevisedAnswer, DraftRevisionNodeTypes.FinalizeRevision, PortfolioRiskMathNodeTypes.PrepareInputs, PortfolioRiskMathNodeTypes.Execute];
    private static AgentNodeCatalogEntry N(string type, string name, string description, string stage, string effect, IReadOnlyList<string> required, IReadOnlyList<string> produced, IReadOnlyList<string> next, bool supportsLoop = false, bool requiresHumanInput = false) => new(new AgentNodeContract(
        type, 1, name, description, stage, effect,
        $"{type}Input", $"{type}Output", required, [], produced, [], next,
        new AgentNodeExecutionPolicy(120, 0), true, supportsLoop, requiresHumanInput));
}
